### ISSUE TITLE
AttributeError: 'module' object has no attribute 'FileHandler' (Blender 3.6.5; addon ver. 1.5.8)

### ISSUE THREAD

**Issue by mixe21** [Al-Hydra/Blender-XFBIN-Importer#4]
The error appears when I want to enable the addon
```
Traceback (most recent call last):
  File "D:\Downloads\blender-3.6.5-windows-7\3.6\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "D:\Downloads\blender-3.6.5-windows-7\3.6\scripts\addons\Blender-XFBIN-Importer\__init__.py", line 20, in <module>
    from .blender.addon import *
  File "D:\Downloads\blender-3.6.5-windows-7\3.6\scripts\addons\Blender-XFBIN-Importer\blender\addon.py", line 8, in <module>
    from .importer import (ImportXFBIN, DropXFBIN, XFBIN_FH_import, menu_func_import, XFBIN_UL_IMPORT_LIST, XFBIN_OT_IMPORT_ADD_FILE,
  File "D:\Downloads\blender-3.6.5-windows-7\3.6\scripts\addons\Blender-XFBIN-Importer\blender\importer.py", line 226, in <module>
    class XFBIN_FH_import(bpy.types.FileHandler):
AttributeError: 'module' object has no attribute 'FileHandler'
```

**I found a solution. Replaced lines 226-227 in importer.py**
```
class XFBIN_FH_import(bpy.types.Operator):
    bl_idname = "import_xfbin.file_handler"
```
It's working fine so far.

**Comment by Al-Hydra** [comment]
I'm sorry but there are no plans to keep support for older versions of blender.
