### ISSUE TITLE
Exception: BinaryReader Error: cannot read farther than buffer length.

### ISSUE THREAD

**Issue by mixe21** [Al-Hydra/Blender-XFBIN-Importer#5]
Got an error when open a file:

Python: Traceback (most recent call last):
  File "D:\Downloads\blender\scripts\addons\Blender-XFBIN-Importer\blender\importer.py", line 161, in execute
    importer.read(context)
  File "D:\Downloads\blender\scripts\addons\Blender-XFBIN-Importer\blender\importer.py", line 251, in read
    self.xfbin = read_xfbin(self.filepath)
  File "D:\Downloads\blender\scripts\addons\Blender-XFBIN-Importer\xfbin_lib\xfbin\xfbin_reader.py", line 21, in read_xfbin
    br_xfbin: BrXfbin = br.read_struct(BrXfbin)
  File "D:\Downloads\blender\scripts\addons\Blender-XFBIN-Importer\xfbin_lib\xfbin\util\binary_reader\binary_reader\binary_reader.py", line 385, in read_struct
    br_struct.__br_read__(self, *args)
  File "D:\Downloads\blender\scripts\addons\Blender-XFBIN-Importer\xfbin_lib\xfbin\structure\br\br_xfbin.py", line 23, in __br_read__
    br_page: BrPage = br.read_struct(BrPage, None, self)
  File "D:\blender\scripts\addons\Blender-XFBIN-Importer\xfbin_lib\xfbin\util\binary_reader\binary_reader\binary_reader.py", line 385, in read_struct
    br_struct.__br_read__(self, *args)
  File "D:\blender\scripts\addons\Blender-XFBIN-Importer\xfbin_lib\xfbin\structure\br\br_xfbin.py", line 334, in __br_read__
    chunk = br_xfbin.chunkTable.get_br_nucc_chunk(br_chunk, br_xfbin.curPageStart)
  File "D:\blender\scripts\addons\Blender-XFBIN-Importer\xfbin_lib\xfbin\structure\br\br_xfbin.py", line 197, in get_br_nucc_chunk
    return BrNuccChunk.create_from_nucc_type(*self.get_props_from_chunk_map(chunk_map), br_chunk.data, br_chunk.nuccId, br_chunk.unk)
  File "D:\blender\scripts\addons\Blender-XFBIN-Importer\xfbin_lib\xfbin\structure\br\br_nucc.py", line 65, in create_from_nucc_type
    return BinaryReader(data, Endian.BIG).read_struct(cls.get_br_nucc_type_from_str(type_str), None, file_path, name, type_str, version, anmvalue)
  File "D:\blender\scripts\addons\Blender-XFBIN-Importer\xfbin_lib\xfbin\util\binary_reader\binary_reader\binary_reader.py", line 385, in read_struct
    br_struct.__br_read__(self, *args)
  File "D:\blender\scripts\addons\Blender-XFBIN-Importer\xfbin_lib\xfbin\structure\br\br_nucc.py", line 32, in __br_read__
    self.init_data(br)
  File "D:\blender\scripts\addons\Blender-XFBIN-Importer\xfbin_lib\xfbin\structure\br\br_nucc.py", line 677, in init_data
    self.entries = br.read_struct(BrAnmEntry, self.entry_count)
  File "D:\blender\scripts\addons\Blender-XFBIN-Importer\xfbin_lib\xfbin\util\binary_reader\binary_reader\binary_reader.py", line 379, in read_struct
    br_struct.__br_read__(self, *args)
  File "D:\blender\scripts\addons\Blender-XFBIN-Importer\xfbin_lib\xfbin\structure\br\br_anm.py", line 116, in __br_read__
    self.curve_headers = br.read_struct(BrAnmCurveHeader, self.curve_count)
  File "D:\blender\scripts\addons\Blender-XFBIN-Importer\xfbin_lib\xfbin\util\binary_reader\binary_reader\binary_reader.py", line 379, in read_struct
    br_struct.__br_read__(self, *args)
  File "D:\blender\scripts\addons\Blender-XFBIN-Importer\xfbin_lib\xfbin\structure\br\br_anm.py", line 74, in __br_read__
    self.keyframe_count = br.read_uint16()
  File "D:\blender\scripts\addons\Blender-XFBIN-Importer\xfbin_lib\xfbin\util\binary_reader\binary_reader\binary_reader.py", line 330, in read_uint16
    return self.__read_type("H")[0]
  File "D:\blender\scripts\addons\Blender-XFBIN-Importer\xfbin_lib\xfbin\util\binary_reader\binary_reader\binary_reader.py", line 232, in __read_type
    raise Exception(
Exception: BinaryReader Error: cannot read farther than buffer length.

Here is file - [1efcmn.out.zip](https://github.com/user-attachments/files/17003642/1efcmn.out.zip)

**Comment by Al-Hydra** [comment]
this has been fixed in version 1.6.4
