### ISSUE TITLE
Python importxfbin error

### ISSUE THREAD

**Issue by ShigureTokisaki** [Al-Hydra/Blender-XFBIN-Importer#7]
Hello, when i import any .xfbin asset into blender. this importer will go wrong.

attributeerror:'mesh' object has no attribute 'create_normals_split'

my blender version is 4.2.3 LTS
and game is Storm 4.
Is where i did mistakes?
```
Python: Traceback (most recent call last):
  File "C:\Users\AI-4090\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\Blender-XFBIN-Importer\blender\importer.py", line 81, in execute
    importer.read(context)
  File "C:\Users\AI-4090\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\Blender-XFBIN-Importer\blender\importer.py", line 150, in read
    self.make_objects(clump, armature_obj, context)
  File "C:\Users\AI-4090\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\Blender-XFBIN-Importer\blender\importer.py", line 387, in make_objects
    overall_mesh.create_normals_split()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Mesh' object has no attribute 'create_normals_split'
```

**Comment by Al-Hydra** [comment]
use the latest beta release
